---
version: 2

jobs:
  build:
    docker:
      - image: udata/circleci:2-alpine
      - image: circleci/mongo:3.6-stretch-ram
      - image: redis:alpine
      - image: udata/elasticsearch:2.4.5
      - image: influxdb:alpine
        environment:
          INFLUXDB_DB: piwik_db
          INFLUXDB_USER: piwik
          INFLUXDB_USER_PASSWORD: piwik
      - image: udata/piwik-test
        environment:
          MYSQL_ROOT_PASSWORD: piwik
          MYSQL_DATABASE: piwik
          MYSQL_USER: piwik
          MYSQL_PASSWORD: piwik
    environment:
      BASH_ENV: /root/.bashrc
      PIWIK_URL: localhost
    steps:
      - checkout
      - run:
          name: Wait for piwik
          command: dockerize -wait tcp://localhost:80 -timeout 2m
      - run:
          name: Compute Python dependencies key
          command: cat requirements/*.pip > python.deps
      - run:
          name: Get the base reference branch
          command: export BASE_BRANCH=$(base_branch)
      - restore_cache:
          keys:
            - py-cache-v13-{{ arch }}-{{ checksum "python.deps" }}
            - py-cache-v13-{{ arch }}-{{ .Branch }}
            - py-cache-v13-{{ arch }}-{{ .Environment.BASE_BRANCH }}
      - run:
          name: Install python dependencies
          command: |
            virtualenv venv
            source venv/bin/activate
            # Workaround to bad transitive dependencies resolution:
            # Install package first then all other dependencies
            pip install -e . || pip install -e .
            pip install -r requirements/develop.pip || pip install -r requirements/develop.pip
      - save_cache:
          key: py-cache-v13-{{ arch }}-{{ checksum "python.deps" }}
          paths:
            - venv
      - save_cache:
          key: py-cache-v13-{{ arch }}-{{ .Branch }}
          paths:
            - venv
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            inv qa test --report
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/
          destination: reports
      - run:
          name: Build a distributable package
          command: |
            source venv/bin/activate
            # Build a wheel release
            if [[ $CIRCLE_TAG ]]; then
                # This is a tagged release
                inv dist
            elif [[ "$CIRCLE_BRANCH" == feature/* ]]; then
                # This is a feature branch
                inv dist -b $CIRCLE_BUILD_NUM+${CIRCLE_BRANCH#*/}
            else
                # This is a simple development build
                inv dist -b $CIRCLE_BUILD_NUM
            fi
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - venv

  publish:
    docker:
      - image: udata/circleci:2-alpine
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Publish on PyPI
          command: |
            source venv/bin/activate
            twine upload --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" dist/*.whl

  github:
    docker:
      - image: udata/circleci:2-alpine
    environment:
      BASH_ENV: /root/.bashrc
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Upload github release
          command: gh_release

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          context: org-global
      - github:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          context: org-global
